language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
before_install:
- npm install -g webpack
install:
- npm install
script:
- npm run build
notifications:
  email:
    recepients:
    - patrick@pburtchaell.com
