language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
  - /^deploy-.*$/
before_install:
- npm install -g grunt-cli bower
install:
- npm install
- bower install
before_script:
- git config --global user.email "patrick@pburtchaell.com"
- git config --global user.name "Patrick Burtchaell"
script: grunt build
after_script:
- echo -e "All done for now\n"
notifications:
  email:
    recepients:
    - patrick@pburtchaell.com
