language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
before_install:
- npm install -g gulp grunt-cli bower
install:
- npm install
- bower install
before_script:
- git config --global user.email "patrick@pburtchaell.com"
- git config --global user.name "Patrick Burtchaell"
script: 
 - gulp default
 - grunt assemble
notifications:
  email:
    recepients:
    - patrick@pburtchaell.com
