export default {
  HEADER_HIRE_ENTRY_POINT: 'HEADER_HIRE_ENTRY_POINT',
  HEADER_HIRE_ENTRY_POINT_HOVER: 'HEADER_HIRE_ENTRY_POINT_HOVER',
  HEADER_HIRE_BUTTON: 'HEADER_HIRE_BUTTON',
  FOOTER_BACK_TO_TOP_LINK: 'FOOTER_BACK_TO_TOP_LINK',
  FOOTER_BACK_TO_PAGE_LINK: 'FOOTER_BACK_TO_PAGE_LINK',
  HIRE_MODULE_BUTTON: 'HIRE_MODULE_BUTTON',
  HIRE_MODULE_BUTTON_HOVER: 'HIRE_MODULE_BUTTON_HOVER',
  HOME_PAGE_LIST_VIEW_ITEM: 'HOME_PAGE_LIST_VIEW_ITEM',
  OUTBOUND_SOCIAL_LINK: 'OUTBOUND_SOCIAL_LINK_HOVER',
  OUTBOUND_PROJECT_LINK_FROM_POST: 'OUTBOUND_PROJECT_LINK_FROM_POST',
  OUTBOUND_PROJECT_LINK_FROM_PROFILE: 'OUTBOUND_PROJECT_LINK_FROM_PROFILE'
};
