# Netlify CMS Configuration
# See more: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: github
  repo: pburtchaell/mttr.design

media_folder: src/content/assets
public_folder: assets

# Content Types
collections:
  - name: projects
    label: Projects
    folder: src/content/projects
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: description
        label: Description
        widget: string
        required: true
      - name: coverImage
        label: Cover Image
        widget: image
        required: true
      - name: coverImageDescription
        label: Cover Image Description
        widget: string
        required: true
      - name: body
        label: Body
        widget: markdown
        required: true
  - name: posts
    label: Posts
    folder: src/content/posts
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: description
        label: Description
        widget: string
        required: true
      - name: body
        label: Body
        widget: markdown
        required: true
