# Netlify CMS Configuration
# See more: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: github
  repo: pburtchaell/pburtchaell.com

media_folder: src/content/assets
public_folder: static

# Content Types
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/content/projects
    create: true
    meta:
      - { name: published, label: Published, widget: boolean, default: false }
      - { name: description, label: Description, widget: string, required: true }
      - { name: date, label: Date, widget: date, required: true }
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: externalLink, label: External Link, widget: string }
      - { name: externalLinkDescription, label: External Link Description, widget: string }
      - { name: body, label: Body, widget: markdown, required: true }
