export const GET_AVAILABILITY = 'GET_AVAILABILITY';
export const GET_AVAILABILITY_PENDING = 'GET_AVAILABILITY_PENDING';
export const GET_AVAILABILITY_FULFILLED = 'GET_AVAILABILITY_FULFILLED';
export const GET_AVAILABILITY_REJECTED = 'GET_AVAILABILITY_REJECTED';
